### ISSUE TITLE
wrong constructor arguments 

### ISSUE THREAD

**Issue by mdtanrikulu** [evmts/tevm-monorepo#1052]
hey there!

I was playing with the `createScript` and provided all necessary arguments directly from contract abi, but when try to retrieve constructor arguments, returned result is incorrect. not sure If I have any good option to debug it on my side, but I am happy to provide more.

abi:  https://github.com/ensdomains/ens-contracts/blob/staging/deployments/mainnet/DNSSECImpl.json

```js
const script = createScript({
  name: 'DNSSECImpl',
  humanReadableAbi: formatAbi(abi),
  bytecode: bytecode,
  deployedBytecode: deployedBytecode,
});

const memoryClient = createMemoryClient();

const { anchors }: any = script.read;

try {
  const anchorResponse = await memoryClient.script(anchors());
  console.log(anchorResponse);
} catch (error) {
  console.log('error', error);
}
```

result: 
```
{
  rawData: "0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000",
  executionGasUsed: 2980n,
  selfdestruct:   Set {},
  gas: 16774235n,
  logs: [],
  createdAddresses:   Set {},
  data: "0x"
}
```

expected:
```
0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000005e00002b000100000e1000244a5c080249aac11d7b6f6446702e54a1607371607a1a41855200fd2ce1cdde32f24e8fb500002b000100000e1000244f660802e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d0000

-----Decoded View---------------
Arg [0] : _anchors (bytes): 0x00002b000100000e1000244a5c080249aac11d7b6f6446702e54a1607371607a1a41855200fd2ce1cdde32f24e8fb500002b000100000e1000244f660802e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d
```

**Comment by roninjin10** [comment]
Thanks for the bug report. Where did the expected result come from? cast call to the network?

Unrelated comment: `const { anchors }: any = script.read;` Unrelated to the bug report but if you `as const` the abi you shouldn't need to have this any

**Comment by mdtanrikulu** [comment]
hey there, thanks for the trick but it actually doesn't help with `formatAbi`, not sure maybe I do something wrong. 

yep, expected result can be retrieved both from cast call or directly from etherscan. seem like the arguments are not concatenated into the deployed bytecodes, hence returns 0x0 for the state filled in constructor. I tried to append arguments at the end of the bytecode manually, but still the same result

**Comment by roninjin10** [comment]
> hey there, thanks for the trick but it actually doesn't help with formatAbi, not sure maybe I do something wrong.

Chances are you are doing something wrong. If you share a repro I can point you in right direction. For context the types here are being driven by ABI type (from the wagmi squad) so it's pretty battle tested.

> 
hey there, thanks for the trick but it actually doesn't help with formatAbi, not sure maybe I do something wrong.

yep, expected result can be retrieved both from cast call or directly from etherscan. seem like the arguments are not concatenated into the deployed bytecodes, hence returns 0x0 for the state set in constructor. I tried to append arguments at the end of the bytecode manually, but still the same result

Ah I see. Yea tevm.script doesn't support constructor arguments. Might be worth marking this down as a feature to add. There are two options available today however.

1. Fork the network. For this option you can just fork the network that has the contract bytecode already deployed

```typescript
const memoryClient = createMemoryClient({fork: {url: 'https://alchemy.infura.quicknode' }});
```

And then you can call the contract with `tevm.contract`

```typescript
const dnsec = createContract({
  name: 'DNSSECImpl',
  humanReadableAbi: formatAbi(abi),
}).withAddress(DNSSEC_ADDRESS);

const res = memoryClient.contract(
  dnsec.read.anchors()
)
```

2. Alternatively you can deploy the contract manually rather than using script

This is a little clunky to do without using viem so we should consider allowing constructor args in tevm.script and also adding a `tevm.deploy` method.

```typescript
import {encodeDeployData} from '@tevm/utils' // can import this from 'tevm/utils' or 'viem' as well

const script = createScript({
  name: 'DNSSECImpl',
  humanReadableAbi: formatAbi(abi),
  bytecode: bytecode,
  deployedBytecode: deployedBytecode,
});

const callData = encodeDeployData({
  abi: script.abi,
  bytecode: script.bytecode,
  args: ['pass', 'constructor', 'args'],
})

const {createdAddresses, txHash} = await memoryClient.call({
  createTransaction: true,
  data: callData,
  from: deployerAddress,
})

// if using latest version you must mine the block too
await memoryClient.mine()
```

**Comment by roninjin10** [comment]
Will try to sneak in a mitigation for this issue in tomorrows release
