### ISSUE TITLE
🐛Bug: `ts-plugin` does not resolve exports for remapped imports installed with forge

### ISSUE THREAD

**Issue by emo-eth** [evmts/tevm-monorepo#1341]
Relative filepaths work; remapped paths do not

Example repo: https://github.com/emo-eth/minrepro

**Comment by roninjin10** [comment]
So is the issue here this?

- LSP works
- Next.js build does not

If so this is expected and something I should do a better job documenting. I just looked in docs and any documentation on this is very buried and impossible to discover.

## TLDR

There are 2 fixes

1. You can code-gen the typescript before running webpack production build `npx tevm-gen . src/Counter.sol`
2. You can turn off typechecking in the next.js config like [here](https://github.com/roninjin10/evmts-next/blob/main/next.config.js#L5C1-L12C9)

## Context

LSP plugins by default only run in your editor and not when command line typescript is running. We have an unreleased way of getitng the command line ts to work (it copies how vue.js works) but this is unreleased at this time.

The first solution of code genning fixes it by adding the ts file for your bundler to resolve which ts will properly see.

The second solution works via turning off typechecking when next.js runs

A better solution will come in future. Will keep issue open until I make a new issue for this

**Comment by roninjin10** [comment]
TODO also add a NEXT.js specific guide as it's the only build that typechecks that I'm aware of

**Comment by emo-eth** [comment]
Sorry, wrote it quickly (& writing this on my phone), the issue is that the LSP doesn't recognize the contract if it imports from a remapped file, eg:

`Module '"../../src/Counter.sol"' has no exported member 'Counter'.ts(2305)`

if it imports from "forge-std/console2.log", so red underline and "any" type. 

Compilation and bundling etc works fine, just typescript lsp within vscode complains

**Comment by roninjin10** [comment]
@emo-eth wasn't able to repro that one both worked fine for me. What editor are you using

**Comment by roninjin10** [comment]
Reproduced bug. The tevm cache MUST not exist when the editor is opened to reproduce

**Comment by roninjin10** [comment]
Error happening
```
Info 103  [20:56:38.603] [tevm-ts-plugin] error: @tevm/ts-plugin: getScriptSnapshotDecorator was unable to resolve dts for /Users/williamcory/minrepro/src/Counter.sol
```

**Comment by roninjin10** [comment]
Error happening

```
Info 101  [20:56:38.603] [tevm-ts-plugin] error: there was an error in tevm plugin resolving .dts
Info 102  [20:56:38.603] [tevm-ts-plugin] error: {
  "_id": "FiberFailure",
  "cause": {
    "_id": "Cause",
    "_tag": "Fail",
    "failure": {
      "_tag": "ReadFileError",
      "name": "ReadFileError"
    }
  }
}
Info 103  [20:56:38.603] [tevm-ts-plugin] error: @tevm/ts-plugin: getScriptSnapshotDecorator was unable to resolve dts for /Users/williamcory/minrepro/src/Counter.sol
Info 104  [20:56:38.603] [tevm-ts-plugin] error: {
  "_id": "FiberFailure",
  "cause": {
    "_id": "Cause",
    "_tag": "Fail",
    "failure": {
      "_tag": "ReadFileError",
      "name": "ReadFileError"
    }
  }
}
```

**Comment by roninjin10** [comment]
Fixed in release 102
